### PR TITLE
Use VNodeProperties#bind as `this` for event handlers

### PR DESCRIPTION
**Pull request by jcfranco**

### CODE REVIEW

**Comment by jcfranco** [comment]
Thanks for the merge! When do you think this will land on NPM?

**Comment by johan-gorter** [comment]
Done.

From now on I will try to make a new npm release every for every merged pull request, this seems to be the most productive for everyone.

**Comment by jcfranco** [comment]
Awesome, thanks again!

**Comment by johan-gorter** [comment]
The currently published version is broken, busy fixing it

**Comment by johan-gorter** [comment]
The latest release now works fine. And I now have a nice script to make new releases as well.

**Pull request merged**
